development:
  dialect: "postgres"
  database: {{ envOr "DB_NAME" "btgql" }}
  host: {{ envOr "DB_HOST" "localhost" }}
  port: {{ envOr "DB_PORT" "5432" }}
  user: {{ envOr "DB_USER" "postgres" }}
  password: {{ envOr "DB_PASSWORD" "postgres" }}

production:
  dialect: "postgres"
  url: {{ env "DB_URL" }}
