# This is a basic workflow to help you get started with Actions

name: Build and push images

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ master ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-images:
      runs-on: ubuntu-latest

      steps:
      #- name: Log into registry
      #  run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin  
      # Check out the repo    
      - name: Checkout
        uses: actions/checkout@v2
      # Build the images 
      - name: Build the docker-compose stack  
        run: docker build . -t ghcr.io/projectblacktube/blacktube-graphql:latest
      # List images that will be pushed
      - name: List images
        run: docker images
      # Push images
      - name: Push images
        run: docker push ghcr.io/projectblacktube/blacktube-graphql:latest
