// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type NewUser struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type NewVideo struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Duration    int    `json:"duration"`
	OwnerID     string `json:"ownerId"`
}
